/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {

    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val nombre: String = "juan"
    var edad: Int = 16


    println("hola $nombre")
    println("$edad años")

    println(App().greeting)
}
